### ISSUE TITLE
swagger同步出错

### ISSUE THREAD

**Issue by NICK-DUAN** [follow-my-heart/yapi-plugin-import-swagger-customize#8]
```
log: 定时器触发, syncJsonUrl:http://9.148.163.161/swagger,合并模式:good
(node:1) UnhandledPromiseRejectionWarning: TypeError: operation[inheritName].some is not a function
    at _loop2 (/yapi/vendors/node_modules/swagger-client/dist/index.js:2635:57)
    at _loop (/yapi/vendors/node_modules/swagger-client/dist/index.js:2644:198)
    at normalizeSwagger (/yapi/vendors/node_modules/swagger-client/dist/index.js:2650:47)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

大佬，能帮忙看下吗？

**Comment by NICK-DUAN** [comment]
好像不是此插件的问题，我先关闭
